application: word-frequency
version: 1
runtime: python27
api_version: 1
threadsafe: no


handlers:
- url: /(.*\.js)
  static_files: js/\1
  upload: js/(.*\.js)
- url: /(.*\.css)
  static_files: css/\1
  upload: css/(.*\.css)  
- url: /.*
  script: main.py
